name = "BlockFactorizations"
uuid = "5c499583-5bfe-4591-9b59-c1e192d48697"
authors = ["Sebastian Ament <sebastianeament@gmail.com>"]
version = "1.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7"
